<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>oz</string>
		<string>mozart</string>
	</array>
	<key>name</key>
	<string>Oz</string>
	<key>scopeName</key>
	<string>source.oz</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(import|define|local|in|end|fun|if|then|else)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
	</array>
</dict>
</plist>
