<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>oz</string>
		<string>mozart</string>
	</array>
	<key>name</key>
	<string>Oz</string>
	<key>scopeName</key>
	<string>source.oz</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(andthen|at|attr|case|catch|choice|class|cond|declare|define|dis|div|do|else|elsecase|elseif|end|export|fail|false|feat|finally|for|from|fun|functor|if|import|in|lazy|local|lock|meth|mod|not|of|or|orelse|prepare|proc|prop|raise|require|self|skip|then|thread|true|try|unit)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
	</array>
</dict>
</plist>
